# Generated by Django 2.0.6 on 2020-07-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=20, verbose_name='车标')),
            ],
            options={
                'verbose_name': '汽车',
                'verbose_name_plural': '汽车',
                'db_table': 'car',
            },
        ),
    ]
